name: Quality

on:
  push:
    branches:
      - "**"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v6

      - name: Install
        uses: ./.github/actions/install

      - name: Build packages
        run: bun run build

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v6

      - name: Install
        uses: ./.github/actions/install

      - name: Build packages
        run: bun run build

      - name: Run tests
        run: bun run test

  format:
    name: Format Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v6

      - name: Run format
        run: bun run format:check

  lint:
    name: Lint Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v6

      - name: Install
        uses: ./.github/actions/install

      - name: Run lint
        run: bun run lint

  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v6

      - name: Install
        uses: ./.github/actions/install

      - name: Run typecheck
        run: bun run typecheck
